### ISSUE TITLE
MelCloud and Homey Bridge

### ISSUE THREAD

**Issue by AndLin67** [OlivierZal/com.melcloud.extension#42]
Hi!
Any plans to update Melcloud app to work with Homey Bridge?

/Anders

**Comment by OlivierZal** [comment]
Hi @AndLin67,

Unfortunately it’s not possible as explained here: https://github.com/OlivierZal/com.melcloud/discussions/8

Kind regards

**Comment by AndLin67** [comment]
Ok!I understand. Thanks for info links./Anders
-------- Originalmeddelande --------Från: Olivier Zalmanski ***@***.***> Datum: 2023-04-16  12:22  (GMT+01:00) Till: "OlivierZal/com.melcloud.extension" ***@***.***> Kopia: AndLin67 ***@***.***>, Mention ***@***.***> Ämne: Re: [OlivierZal/com.melcloud.extension] MelCloud and Homey Bridge
  (Issue #42) 
Hi @AndLin67,
Unfortunately it’s not possible as explained here: OlivierZal/com.melcloud#8
Kind regards
